"""Build dependency-free GitHub Pages pages from shared components."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent.parent
VERSION = '20261005-b2b'
NAV = [('/#result', 'Результат'), ('/kak-my-rabotaem/', 'Как работаем'), ('/programma/', 'Программа'), ('/podbor-eksperta/', 'Эксперт'), ('/#price', 'Бюджет')]

def header(path):
    links = ''.join(f'<a href="{url}"'+(' aria-current="page"' if url == path else '')+f'>{name}</a>' for url, name in NAV)
    return f'''<a class="skip-link" href="#content">Перейти к содержанию</a>
<header class="site-header"><div class="container header-inner">
<a class="brand" href="/" aria-label="North Refresh — главная"><span class="brand-mark" aria-hidden="true">NR</span><span>North Refresh</span></a>
<nav id="site-nav" class="site-nav" aria-label="Основная навигация">{links}<a class="nav-contact" href="/kontakty/">Контакты</a></nav>
<a class="header-action" href="/#contact">Обсудить задачу <span aria-hidden="true">↗</span></a>
<button class="menu-toggle" type="button" aria-controls="site-nav" aria-label="Открыть меню" aria-expanded="false"><span></span></button>
</div></header>'''

def footer():
    return '''<footer class="site-footer"><div class="container footer-grid">
<div><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">NR</span><span>North Refresh</span></a><p>Выездные стратегические сессии<br>для собственников и управленческих команд.</p></div>
<nav aria-label="Навигация в подвале"><a href="/kak-my-rabotaem/">Как мы работаем</a><a href="/programma/">Программа и результаты</a><a href="/podbor-eksperta/">Подбор эксперта</a><a href="/kontakty/">Контакты</a></nav>
<div class="footer-contact"><a href="mailto:max_brus@mail.ru">max_brus@mail.ru</a><p>Ленинградская область и Карелия.<br>Площадку выбираем под задачу команды.</p></div>
</div><div class="container footer-bottom"><span>© North Refresh, 2026</span><span>Подготовка · Сессия · План исполнения</span></div></footer>'''

def contact(compact=False):
    return '''<section class="section contact-section" id="contact" aria-labelledby="contact-title"><div class="container contact-grid">
<div><p class="eyebrow light">Первый разговор</p><h2 id="contact-title">Какую задачу<br>нужно решить<br>вашей команде?</h2><p class="contact-lead">Обсудим ситуацию, состав участников и ожидаемый результат. Определим, подходит ли выездная сессия и что нужно для подготовки предложения.</p><p class="contact-small">Даты, площадку и подробный бюджет можно уточнить после знакомства.</p><a class="email-link" href="mailto:max_brus@mail.ru">max_brus@mail.ru <span aria-hidden="true">↗</span></a></div>
<form id="contact-form" class="contact-form" action="https://formspree.io/f/moeangbe" method="post">
<h3>Обсудить задачу</h3><p class="form-intro">Оставьте контакт — свяжемся для первого разговора.</p>
<div class="honeypot" aria-hidden="true"><label for="website">Оставьте это поле пустым</label><input id="website" name="_gotcha" type="text" tabindex="-1" autocomplete="off"></div>
<div class="form-row"><label for="name">Имя <span>*</span><input id="name" name="name" autocomplete="name" placeholder="Как к вам обращаться" required maxlength="120"></label><label for="company">Компания<input id="company" name="company" autocomplete="organization" placeholder="Название компании" maxlength="180"></label></div>
<label for="contact-detail">Email, телефон или Telegram <span>*</span><input id="contact-detail" name="contact" autocomplete="off" placeholder="Удобный способ связи" required minlength="5" maxlength="180" aria-describedby="contact-hint"></label><p class="field-hint" id="contact-hint">Достаточно одного контакта.</p>
<label for="task">Коротко о задаче <span class="optional">необязательно</span><textarea id="task" name="task" rows="3" placeholder="Что нужно обсудить или согласовать?" maxlength="4000"></textarea></label>
<p class="form-privacy">Используем указанные данные для ответа на ваш запрос. Не отправляйте через форму конфиденциальные материалы компании.</p>
<button class="button button-primary button-full" type="submit">Обсудить задачу <span aria-hidden="true">↗</span></button>
<p class="form-note" id="form-note" role="status" aria-live="polite">Обязательные поля — имя и контакт.</p>
<noscript><p class="form-note">После отправки откроется страница сервиса приёма заявок. Также можно написать на email.</p></noscript>
</form></div></section>'''

def heading(kicker, title, lead=''):
    return f'<div class="section-heading"><p class="eyebrow">{kicker}</p><div><h2>{title}</h2>'+(f'<p class="section-lead">{lead}</p>' if lead else '')+'</div></div>'

def pagehero(kicker, title, lead, aside=''):
    return f'<section class="container page-hero"><p class="breadcrumb"><a href="/">Главная</a><span aria-hidden="true"> / </span>{kicker}</p><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="page-lead">{lead}</p><div class="hero-actions"><a class="button button-primary" href="/#contact">Обсудить задачу <span aria-hidden="true">↗</span></a>{aside}</div></section>'

def write(path, title, description, content):
    schema = {'@context':'https://schema.org', '@graph':[{'@type':'Organization','@id':'https://northrefresh.ru/#organization','name':'North Refresh','url':'https://northrefresh.ru/','email':'max_brus@mail.ru'}, {'@type':'WebPage','name':title,'url':'https://northrefresh.ru'+path,'inLanguage':'ru-RU','publisher':{'@id':'https://northrefresh.ru/#organization'}}]}
    html = f'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} | North Refresh</title><meta name="description" content="{description}"><meta name="theme-color" content="#173d31">
<link rel="canonical" href="https://northrefresh.ru{path}"><link rel="icon" href="/favicon.svg" type="image/svg+xml">
<meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="North Refresh"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://northrefresh.ru{path}"><meta property="og:image" content="https://northrefresh.ru/north-real-fog.webp">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{title}"><meta name="twitter:description" content="{description}"><meta name="twitter:image" content="https://northrefresh.ru/north-real-fog.webp">
<link rel="stylesheet" href="/site.css?v={VERSION}"><script defer src="/site.js?v={VERSION}"></script><script type="application/ld+json">{json.dumps(schema, ensure_ascii=False)}</script></head>
<body>{header(path)}<main id="content">{content}</main>{footer()}</body></html>'''
    dest = ROOT / path.strip('/') / 'index.html' if path != '/' else ROOT / 'index.html'
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html)

HOME = '''
<section class="container hero" id="top" aria-labelledby="hero-title">
<div class="hero-copy"><p class="eyebrow">Для собственников, CEO и управленческих команд</p><h1 id="hero-title">Согласовать<br>приоритеты бизнеса<br>и план действий<br><em>команды.</em></h1><p class="hero-lead">Выездные стратегические сессии. Разбираем задачу, подбираем эксперта и организуем работу — от подготовки до решений и плана на 90 дней.</p><div class="hero-actions"><a class="button button-primary" href="#contact">Обсудить задачу <span aria-hidden="true">↗</span></a><a class="text-link" href="/programma/">Пример программы и результатов <span aria-hidden="true">→</span></a></div><p class="hero-note">Первый шаг — разговор о вашей задаче.</p></div>
<div class="hero-proof"><div class="proof-top"><span class="eyebrow light">Результат работы</span><span class="proof-index">NR / 01</span></div><div class="roadmap-preview"><div class="doc-header"><span>ПЛАН ИСПОЛНЕНИЯ</span><span>90 ДНЕЙ</span></div><h2>От договорённостей<br>к конкретным действиям</h2><div class="doc-row"><span>01</span><div><strong>Приоритеты</strong><p>Что делаем в первую очередь</p></div></div><div class="doc-row"><span>02</span><div><strong>Ответственность</strong><p>Кто ведёт каждую инициативу</p></div></div><div class="doc-row"><span>03</span><div><strong>Сроки и метрики</strong><p>Когда и как проверяем выполнение</p></div></div><div class="doc-foot"><span class="status-dot"></span>Пример структуры результата</div></div><div class="proof-bottom"><p>Сначала вопрос бизнеса.<br>Затем программа и площадка.</p><span aria-hidden="true">↗</span></div></div>
</section>
<div class="container principles"><span>Индивидуальная программа</span><span>Эксперт под задачу</span><span>Организация выезда</span><span>План исполнения</span></div>
<section class="section" id="about"><div class="container">'''+heading('Когда обращаться', 'Когда обычных совещаний<br>уже недостаточно', 'Сессия нужна, когда вопрос требует совместного решения собственника и руководителей.')+'''
<div class="situations-grid"><article><span class="number">01</span><h3>Разные приоритеты</h3><p>Руководители предлагают разные направления и конкурируют за одни ресурсы.</p></article><article><span class="number">02</span><h3>Решение откладывается</h3><p>Вопрос возвращается на совещания, но команда не выбирает порядок действий.</p></article><article><span class="number">03</span><h3>Размыта ответственность</h3><p>Задачи переходят между функциями. Непонятно, кто отвечает за конечный результат.</p></article><article><span class="number">04</span><h3>Предстоят изменения</h3><p>Нужно согласовать новый продукт, структуру управления или план следующего периода.</p></article></div></div></section>
<section class="section result-section" id="result"><div class="container">'''+heading('Что получает компания', 'Решения, которые можно<br>передать в работу', 'Состав итоговых материалов согласуем до сессии. В них должны быть понятны решения, ответственность и порядок проверки исполнения.')+'''
<div class="result-grid"><article><span class="number">01 / ВЫБОР</span><h3>Согласованные приоритеты</h3><p>Что команда делает первым, что откладывает и по каким критериям выбирает.</p></article><article><span class="number">02 / ФИКСАЦИЯ</span><h3>Протокол решений</h3><p>Принятые решения, ограничения и вопросы, для которых ещё нужны данные.</p></article><article><span class="number">03 / ИСПОЛНЕНИЕ</span><h3>План на 90 дней</h3><p>Действия, ответственные, сроки, необходимые ресурсы и критерии выполнения.</p></article></div>
<div class="section-tail"><p>Решения выполняет команда заказчика. Формат последующего сопровождения фиксируем в предложении.</p><a class="text-link" href="/programma/#roadmap">Посмотреть пример плана <span aria-hidden="true">→</span></a></div></div></section>
<section class="section" id="process"><div class="container">'''+heading('Как устроена работа', 'Подготовка определяет<br>качество сессии')+'''
<ol class="process-list"><li><span class="number">01</span><h3>Диагностика задачи</h3><p>Уточняем ситуацию, участников, необходимые данные и ожидаемый результат.</p></li><li><span class="number">02</span><h3>Программа и эксперт</h3><p>Предлагаем специалиста, рабочие вопросы и логику сессий под задачу компании.</p></li><li><span class="number">03</span><h3>Выездная сессия</h3><p>Команда сравнивает варианты, обсуждает ограничения и принимает решения.</p></li><li><span class="number">04</span><h3>План и сопровождение</h3><p>Оформляем итоги. Согласуем контрольные встречи и порядок проверки исполнения.</p></li></ol><div class="section-tail"><p>Программа, состав участников и длительность определяются задачей.</p><a class="text-link" href="/kak-my-rabotaem/">Подробнее о процессе <span aria-hidden="true">→</span></a></div></div></section>
<section class="expert-band"><div class="container expert-grid"><div><p class="eyebrow light">Подбор эксперта</p><h2>Кто работает<br>с вашей командой</h2><p>Фасилитатор помогает согласовать решения. Профильный эксперт привносит опыт в конкретном вопросе бизнеса. Выбор зависит от задачи.</p><a class="text-link" href="/podbor-eksperta/">Как выбираем специалиста <span aria-hidden="true">→</span></a></div><div class="expert-criteria"><div><span>01</span><p>Опыт, соответствующий задаче компании</p></div><div><span>02</span><p>Работа с собственниками и руководителями</p></div><div><span>03</span><p>Профиль и подход — на согласование заказчику</p></div><div><span>04</span><p>Понятная роль в подготовке и проведении</p></div></div></div></section>
<section class="section" id="program"><div class="container example-grid"><div><p class="eyebrow">Посмотреть продукт</p><h2>Как выглядит<br>работа на практике</h2><p class="section-lead">Демонстрационная задача: выбрать приоритеты квартала, распределить ресурсы и согласовать ответственность.</p><a class="button button-outline" href="/programma/">Открыть программу и пример результатов <span aria-hidden="true">→</span></a><p class="small-note">Учебный пример. Не клиентский кейс.</p></div><div class="example-card"><div><span>ДО ВЫЕЗДА</span><strong>Запрос, интервью, исходные данные</strong></div><div><span>ДЕНЬ 1</span><strong>Общая картина и критерии выбора</strong></div><div><span>ДЕНЬ 2</span><strong>Варианты, ресурсы и приоритеты</strong></div><div><span>ДЕНЬ 3</span><strong>Решения и план исполнения</strong></div><div><span>ПОСЛЕ</span><strong>Проверка действий по согласованному графику</strong></div></div></div></section>
<section class="section budget-section" id="price"><div class="container budget-grid"><div><p class="eyebrow">Бюджет проекта</p><h2>Содержательная работа<br>и организация выезда</h2><p class="section-lead">В предложении разделяем подготовку и проведение сессии, организацию выезда и дополнительные услуги.</p><a class="text-link" href="/kak-my-rabotaem/#scope">Что входит в проект <span aria-hidden="true">→</span></a></div><div class="budget-card"><span class="eyebrow">Ориентир для базового выезда</span><strong class="budget-number">1,44–1,92 <span>млн ₽</span></strong><p>Три дня, две ночи, 12–24 участника.<br>Ориентир за проект, а не за человека.</p><div class="budget-divider"></div><p>Итоговый бюджет зависит от объёма подготовки, специалистов, площадки и размещения. Сопровождение после выезда указываем отдельной строкой.</p><p class="small-note">Для небольших команд и другой длительности — индивидуальная программа и расчёт.</p><a class="button button-primary button-full" href="#contact">Обсудить задачу и бюджет <span aria-hidden="true">↗</span></a></div></div></section>
<section class="section venue-section" id="included"><div class="container venue-grid"><div class="venue-image"><img src="/north-real-lake.webp" alt="Озеро и лес в северном регионе" loading="lazy" width="1200" height="800"><span>Ленинградская область / Карелия</span></div><div><p class="eyebrow">Организация</p><h2>Команда работает.<br>Выезд организуем мы.</h2><p class="section-lead">Подбираем площадку с закрытым рабочим пространством, согласуем проживание, питание и общий график. Продюсер координирует подготовку и проведение.</p><p>Для дороги предлагаем варианты перевозчиков и согласуем время прибытия. Договор и оплату перевозки заказчик оформляет напрямую; транспорт не включён в базовый бюджет.</p><a class="text-link" href="/kak-my-rabotaem/#scope">Состав и границы услуги <span aria-hidden="true">→</span></a></div></div></section>
<section class="section faq-section" id="faq"><div class="container faq-grid"><div><p class="eyebrow">Перед разговором</p><h2>Вопросы<br>заказчика</h2></div><div class="faq-list">
<details><summary>Почему выезд, а не встреча в офисе?</summary><p>Выезд позволяет выделить непрерывное время и работать без параллельных операционных встреч. Его целесообразность обсуждаем на первом разговоре: не каждой задаче нужны три дня и поездка.</p></details>
<details><summary>Можно приехать командой меньше 12 человек?</summary><p>Да. Состав определяется тем, кто участвует в принятии и исполнении решений. Для небольшой команды предложим отдельную программу и смету.</p></details>
<details><summary>Как понять, кто будет вести сессию?</summary><p>После разбора задачи предлагаем специалиста, его профиль и подход к работе. Кандидат и его роль согласуются с заказчиком до подтверждения программы.</p></details>
<details><summary>Что потребуется подготовить компании?</summary><p>Список зависит от вопроса: цели, показатели, инициативы, ограничения по ресурсам. На этапе подготовки определяем необходимые материалы и участников.</p></details>
<details><summary>Что произойдёт, если данных для решения недостаточно?</summary><p>Фиксируем недостающие данные, ответственного и срок проверки. Не подменяем решение предположением. Сессия не заменяет исследование рынка или полный аудит компании.</p></details>
<details><summary>Как работать с конфиденциальными вопросами?</summary><p>До передачи материалов согласуем состав участников, правила доступа, фиксации и хранения. Условия конфиденциальности определяем с заказчиком до начала содержательной подготовки.</p></details>
<details><summary>Что входит в сопровождение после выезда?</summary><p>Можно согласовать контрольные встречи: проверить выполнение первых действий, разобрать препятствия и обновить план. Период, количество встреч, участники и стоимость фиксируются в предложении.</p></details>
<details><summary>Как согласуются оплата, перенос и отмена?</summary><p>Порядок оплаты, условия переноса и отмены указываем в договоре и предложении до подтверждения заказа. Они зависят в том числе от условий площадки и специалистов.</p></details>
</div></div></section>'''+contact()

PROCESS = pagehero('Как мы работаем', 'От запроса собственника<br>до плана исполнения', 'Согласуем задачу и ожидаемый результат до выезда. Подготовка, эксперт и программа должны соответствовать вопросу, который предстоит решить.')+'''
<section class="section section-topless"><div class="container steps-detail">
<article><div><span class="number">01 / ДИАГНОСТИКА</span><h2>Определить задачу</h2></div><div><p>Первый разговор — о ситуации компании, а не о выборе отеля. Уточняем, какое решение откладывается, кто должен его принять и что мешает договориться.</p><ul><li>Ожидаемый результат и границы вопроса.</li><li>Участники, их полномочия и разные позиции.</li><li>Исходные данные и ограничения по ресурсам.</li></ul><p class="step-output"><strong>На выходе:</strong> согласованный запрос и перечень материалов для подготовки.</p></div></article>
<article><div><span class="number">02 / ПРОЕКТИРОВАНИЕ</span><h2>Собрать программу</h2></div><div><p>Подбираем ведущего и при необходимости профильного эксперта. Предлагаем последовательность рабочих блоков и документы, которые команда подготовит по итогам.</p><p>Длительность определяется задачей. Базовый выезд — три дня и две ночи; для другого состава команды и объёма работы делаем отдельный расчёт.</p><p class="step-output"><strong>На выходе:</strong> кандидат специалиста, программа, состав результатов и предварительная смета.</p><a class="text-link" href="/podbor-eksperta/">Порядок подбора эксперта <span aria-hidden="true">→</span></a></div></article>
<article><div><span class="number">03 / ПОДГОТОВКА</span><h2>Собрать контекст</h2></div><div><p>Согласуем необходимые интервью, материалы и данные компании. Уточняем вопросы, по которым позиции участников различаются, и правила работы с конфиденциальной информацией.</p><p>Продюсер параллельно согласует площадку, размещение, питание и график. Все включённые услуги и доплаты отражаются в предложении.</p><p class="step-output"><strong>На выходе:</strong> материалы для сессии, подробная программа и подтверждённые организационные условия.</p></div></article>
<article><div><span class="number">04 / СЕССИЯ</span><h2>Принять решения</h2></div><div><p>Сверяем факты, сравниваем варианты по согласованным критериям и обсуждаем ресурсы. Ведущий помогает удерживать предмет разговора и фиксировать договорённости.</p><p>Решения принимают собственник и уполномоченные руководители. Если фактов недостаточно, определяем порядок дополнительной проверки.</p><p class="step-output"><strong>На выходе:</strong> выбранные приоритеты, протокол решений и план действий.</p></div></article>
<article><div><span class="number">05 / ПОСЛЕ ВЫЕЗДА</span><h2>Проверить исполнение</h2></div><div><p>Оформляем и передаём итоговые материалы. При согласованном сопровождении проводим контрольные встречи: проверяем первые действия, обсуждаем препятствия и обновляем план.</p><p>Количество встреч, период сопровождения, состав участников и стоимость определяются в предложении. Исполнение и коммерческий результат остаются ответственностью команды заказчика.</p><p class="step-output"><strong>На выходе:</strong> актуальный план и понятный порядок проверки исполнения.</p></div></article>
</div></section>
<section class="section result-section" id="scope"><div class="container">'''+heading('Состав проекта', 'Что согласуем<br>до подтверждения')+'''
<div class="scope-grid"><article><h3>Содержательная работа</h3><ul><li>Диагностика запроса и объём подготовки.</li><li>Программа, ведущий и профильные специалисты.</li><li>Проведение рабочих сессий.</li><li>Протокол решений и план исполнения.</li><li>Состав и бюджет последующего сопровождения.</li></ul></article><article><h3>Организация выезда</h3><ul><li>Площадка и закрытое рабочее пространство.</li><li>Проживание и тип размещения.</li><li>Питание и перерывы между сессиями.</li><li>Материалы, оборудование и координация.</li><li>Время прибытия и условия дополнительных услуг.</li></ul></article></div><div class="scope-note"><strong>Транспорт — отдельный договор.</strong><p>Помогаем выбрать перевозчика и согласовать расписание. Заказчик заключает договор и оплачивает перевозку напрямую. Дополнительные ночи, одноместное размещение и другие услуги указываем в смете; их состав зависит от выбранной комплектации.</p></div></div></section>
<section class="section"><div class="container responsibility-grid"><div><p class="eyebrow">Ответственность</p><h2>У каждой части<br>есть ответственный</h2></div><div><article><h3>Продюсер North Refresh</h3><p>Координирует проект, площадку, подрядчиков и организационные условия. Держит единый график подготовки и проведения.</p></article><article><h3>Ведущий рабочей части</h3><p>Проектирует сессии, работает с обсуждением и помогает оформить решения. Профильный эксперт привлекается, если задача требует специального опыта.</p></article><article><h3>Заказчик и управленческая команда</h3><p>Предоставляют исходные данные, принимают решения в рамках своих полномочий и выполняют согласованный план.</p></article></div></div></section>'''+contact()

EXPERT = pagehero('Подбор эксперта', 'Специалист под задачу.<br>Выбор — до сессии.', 'Сначала разбираем вопрос компании. Затем предлагаем специалиста и объясняем, какой опыт и подход нужны для этой работы.')+'''
<section class="section section-topless"><div class="container">'''+heading('Роли в рабочей части', 'Разным вопросам<br>нужны разные специалисты')+'''
<div class="role-grid"><article><span class="number">01</span><h3>Фасилитатор</h3><p>Помогает команде сравнить позиции, выработать критерии выбора и согласовать решения. Не подменяет полномочия собственника и руководителей.</p><div class="role-task">Когда нужен: разные приоритеты, затянувшиеся обсуждения, распределение ответственности.</div></article><article><span class="number">02</span><h3>Профильный эксперт</h3><p>Привносит практический опыт в конкретном вопросе: например, коммерческая модель, организация управления или операционные процессы.</p><div class="role-task">Когда нужен: для оценки вариантов требуется специальный опыт, которого не хватает внутри команды.</div></article></div><p class="section-lead narrow">В одном проекте роли могут сочетаться. Состав специалистов определяется после разбора задачи и отражается в смете.</p></div></section>
<section class="section result-section"><div class="container">'''+heading('Критерии выбора', 'Что проверяем<br>при подборе')+'''
<div class="situations-grid"><article><span class="number">01</span><h3>Соответствие задаче</h3><p>Релевантные проекты и предметный опыт. Известность сама по себе не основание для выбора.</p></article><article><span class="number">02</span><h3>Уровень участников</h3><p>Опыт взаимодействия с собственниками и руководителями, работа с разногласиями и сложными решениями.</p></article><article><span class="number">03</span><h3>Подход к подготовке</h3><p>Какие данные нужны, как устроены рабочие блоки и что специалист считает достижимым результатом.</p></article><article><span class="number">04</span><h3>Качество фиксации</h3><p>Как оформляются решения, действия, ответственность и вопросы для дальнейшей проверки.</p></article></div></div></section>
<section class="section"><div class="container definition-grid"><div><p class="eyebrow">Согласование</p><h2>Заказчик понимает,<br>кого мы предлагаем<br>и почему</h2></div><div><p class="section-lead">До утверждения программы предоставляем профиль предложенного специалиста, описание его роли и подхода к задаче.</p><ol class="plain-list"><li>Разбираем запрос и определяем необходимый опыт.</li><li>Предлагаем кандидата и объясняем соответствие.</li><li>Согласуем рабочие вопросы, подготовку и результаты.</li><li>Фиксируем участие и условия в предложении.</li></ol><p>При необходимости согласуем предварительный разговор со специалистом. Если кандидат не подходит, возвращаемся к подбору до подтверждения программы.</p><a class="text-link" href="/kak-my-rabotaem/">Как готовится весь проект <span aria-hidden="true">→</span></a></div></div></section>'''+contact()

PROGRAM = pagehero('Программа и результаты', 'Один вопрос бизнеса.<br>Понятная логика работы.', 'Учебный пример для управленческой команды: выбрать приоритеты квартала, распределить ресурсы и назначить ответственных.', '<a class="text-link" href="#roadmap">Перейти к примеру плана <span aria-hidden="true">↓</span></a>')+'''
<div class="container example-notice"><strong>Демонстрационный пример, не клиентский кейс.</strong><p>Показывает устройство программы и документов. Даты, площадка, состав участников и содержание реального проекта согласуются отдельно.</p></div>
<section class="section"><div class="container definition-grid"><div><p class="eyebrow">Исходная ситуация</p><h2>Инициатив много.<br>Ресурсы ограничены.</h2></div><div><p class="section-lead">У руководителей разные предложения на следующий квартал. Единого порядка запуска нет. Одни и те же люди нужны сразу нескольким проектам.</p><p><strong>Вопрос сессии:</strong> какие инициативы запускаем в ближайшие 90 дней, какие откладываем и кто отвечает за выполнение?</p><p><strong>До выезда:</strong> собираем перечень инициатив, доступные ресурсы, текущие показатели и ограничения. Уточняем позиции участников и полномочия для принятия решений.</p></div></div></section>
<section class="section result-section"><div class="container">'''+heading('Три дня / пример', 'От общей картины<br>к согласованным действиям')+'''
<div class="day-grid"><article><span class="number">ДЕНЬ 1</span><h3>Факты и критерии</h3><p>Сверяем ситуацию, список инициатив и ограничения. Определяем критерии выбора и вопросы, по которым взгляды расходятся.</p><div class="day-output"><strong>Итог</strong><p>Общий список вариантов и согласованные критерии приоритета.</p></div></article><article><span class="number">ДЕНЬ 2</span><h3>Выбор и ресурсы</h3><p>Сравниваем варианты, обсуждаем риски и зависимости. Выбираем инициативы, на которые команда готова выделить ресурсы.</p><div class="day-output"><strong>Итог</strong><p>Приоритеты квартала, отложенные инициативы и предварительное распределение ресурсов.</p></div></article><article><span class="number">ДЕНЬ 3</span><h3>План исполнения</h3><p>Назначаем владельцев инициатив, определяем первые действия, сроки и критерии выполнения. Согласуем контрольные точки.</p><div class="day-output"><strong>Итог</strong><p>Протокол решений и план на 90 дней.</p></div></article></div><p class="small-note">Перерывы, питание и время вне рабочих блоков закладываем в график. Рабочая нагрузка определяется задачей и составом команды.</p></div></section>
<section class="section" id="roadmap"><div class="container">'''+heading('Пример документа', 'План на 90 дней', 'Каждая строка связывает действие с ответственностью, сроком и проверяемым результатом. Целевые значения определяются на основе данных компании.')+'''
<div class="table-wrap" role="region" aria-label="Пример плана исполнения — таблица с горизонтальной прокруткой" tabindex="0"><table class="roadmap-table"><caption>Учебный пример: подготовка пилота нового продукта</caption><thead><tr><th scope="col">Действие</th><th scope="col">Ответственный</th><th scope="col">Срок</th><th scope="col">Проверка результата</th></tr></thead><tbody><tr><td>Согласовать экономику и лимит бюджета пилота</td><td>Финансовый директор</td><td>День 7</td><td>Утверждены расчёт маржи, расходы и лимит финансирования</td></tr><tr><td>Определить клиентский сегмент и условия теста</td><td>Коммерческий директор</td><td>День 14</td><td>Зафиксированы сегмент, предложение и целевые показатели теста</td></tr><tr><td>Провести пилот и собрать фактические данные</td><td>Руководитель продукта</td><td>День 45</td><td>Подготовлен отчёт: продажи, маржа, обратная связь и загрузка команды</td></tr><tr><td>Принять решение о продолжении</td><td>CEO и владельцы функций</td><td>День 60</td><td>Решение сопоставлено с критериями, установленными до пилота</td></tr><tr><td>Проверить выполнение решений квартала</td><td>CEO</td><td>День 90</td><td>Сверены план и факт, определены действия следующего периода</td></tr></tbody></table></div>
<div class="document-pair"><article><p class="eyebrow">Протокол решений</p><h3>Что фиксируем отдельно</h3><ul><li>Что утверждено и кем.</li><li>Какие инициативы отложены и почему.</li><li>Какие ограничения действуют.</li><li>Какие вопросы требуют дополнительных данных.</li></ul></article><article><p class="eyebrow">Контрольные встречи</p><h3>Как возвращаемся к плану</h3><p>Проверяем выполнение первых действий, препятствия и изменения исходных условий. График и участие North Refresh согласуются отдельно.</p><p>В этом примере возможны контрольные точки на 30-й и 90-й день. Они не являются стандартом для всех проектов.</p></article></div></div></section>
<section class="section budget-section"><div class="container definition-grid"><div><p class="eyebrow">Рамки результата</p><h2>Что сессия<br>может обеспечить</h2></div><div><p class="section-lead">Подготовленное обсуждение, фиксацию решений и план исполнения в согласованном объёме.</p><p>Она не заменяет отдельное исследование рынка, полный аудит бизнеса и последующую работу команды. Рост выручки или прибыли зависит от принятых решений и их исполнения.</p><a class="text-link" href="/kak-my-rabotaem/">Подготовка и ответственность <span aria-hidden="true">→</span></a></div></div></section>'''+contact()

CONTACTS = pagehero('Контакты', 'Начнём с задачи<br>вашей команды.', 'Для первого разговора достаточно описать ситуацию и оставить удобный контакт. Даты и площадку можно выбрать после обсуждения.', '<a class="text-link" href="mailto:max_brus@mail.ru">Написать на email <span aria-hidden="true">↗</span></a>')+'''
<section class="section section-topless"><div class="container contact-info-grid"><article><p class="eyebrow">Прямой контакт</p><h3><a href="mailto:max_brus@mail.ru">max_brus@mail.ru</a></h3><p>North Refresh — подготовка и организация выездных стратегических сессий.</p></article><article><p class="eyebrow">География выездов</p><h3>Ленинградская область<br>и Карелия</h3><p>Площадку выбираем по рабочим условиям, приватности, составу команды и доступности.</p></article><article><p class="eyebrow">До заказа</p><h3>Предложение и договор</h3><p>Согласуем задачу, специалиста, программу и смету. Реквизиты исполнителя, условия оплаты, переноса и отмены предоставляются до подтверждения заказа.</p></article></div></section>'''+contact()

write('/', 'Выездные стратегические сессии для собственников и команд', 'North Refresh: диагностика задачи, подбор эксперта, организация выездной сессии и план на 90 дней с ответственными, сроками и метриками.', HOME)
write('/kak-my-rabotaem/', 'Как мы готовим и проводим стратегическую сессию', 'Диагностика, программа, эксперт, подготовка команды, проведение и сопровождение. Состав работы и ответственность North Refresh.', PROCESS)
write('/podbor-eksperta/', 'Подбор эксперта и фасилитатора под задачу компании', 'Критерии подбора и согласования специалиста для стратегической сессии. Роли фасилитатора, профильного эксперта и заказчика.', EXPERT)
write('/programma/', 'Пример программы стратегической сессии и плана на 90 дней', 'Демонстрационная задача, логика трёх дней, протокол решений и пример плана исполнения. Учебный пример North Refresh.', PROGRAM)
write('/kontakty/', 'Обсудить задачу управленческой команды', 'Свяжитесь с North Refresh для обсуждения выездной стратегической сессии. Задача, ожидаемые результаты, состав команды и бюджет.', CONTACTS)

# Legacy routes retain inbound links without retaining the previous product copy.
for path, target in [('/korporativnyy-retrit/', '/'), ('/strategicheskaya-sessiya/', '/')]:
    dest = ROOT / path.strip('/') / 'index.html'
    dest.write_text(f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>North Refresh — стратегические сессии</title><link rel="canonical" href="https://northrefresh.ru{target}"><meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url={target}"></head><body><p>Страница обновлена. <a href="{target}">Перейти на сайт North Refresh</a></p></body></html>''')

notfound = pagehero('Страница не найдена', 'Вернёмся<br>к вашей задаче.', 'Возможно, адрес изменился. На главной странице — продукт, процесс работы и способы связи.', '<a class="text-link" href="/">На главную <span aria-hidden="true">→</span></a>')
write('/404/', 'Страница не найдена', 'Перейти на главную страницу North Refresh.', notfound)
(ROOT/'404.html').write_text((ROOT/'404/index.html').read_text())
urls = ['/', '/kak-my-rabotaem/', '/podbor-eksperta/', '/programma/', '/kontakty/']
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>https://northrefresh.ru{p}</loc></url>\n' for p in urls)+'</urlset>\n')
print('Built 5 pages, 2 legacy redirects and 404; updated sitemap.')
