"""Build dependency-free GitHub Pages pages from shared components."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent.parent
VERSION = '20261005-brand-copy'
NAV = [('/#result', 'Результат'), ('/kak-my-rabotaem/', 'Как работаем'), ('/programma/', 'Программа'), ('/podbor-eksperta/', 'Эксперт'), ('/#price', 'Бюджет')]

def header(path):
    links = ''.join(f'<a href="{url}"'+(' aria-current="page"' if url == path else '')+f'>{name}</a>' for url, name in NAV)
    return f'''<a class="skip-link" href="#content">Перейти к содержанию</a>
<header class="site-header"><div class="container header-inner">
<a class="brand" href="/" aria-label="North Refresh — главная"><span class="brand-mark" aria-hidden="true">NR</span><span>North Refresh</span></a>
<nav id="site-nav" class="site-nav" aria-label="Основная навигация">{links}<a class="nav-contact" href="/kontakty/">Контакты</a></nav>
<a class="header-action" href="#contact">Обсудить задачу <span aria-hidden="true">↗</span></a>
<button class="menu-toggle" type="button" aria-controls="site-nav" aria-label="Открыть меню" aria-expanded="false"><span></span></button>
</div></header>'''

def footer():
    return '''<footer class="site-footer"><div class="container footer-grid">
<div><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">NR</span><span>North Refresh</span></a><p>Выездные стратегические сессии <br>для собственников и управленческих команд.</p></div>
<nav aria-label="Навигация в подвале"><a href="/kak-my-rabotaem/">Как мы работаем</a><a href="/programma/">Программа и результаты</a><a href="/podbor-eksperta/">Подбор эксперта</a><a href="/kontakty/">Контакты</a></nav>
<div class="footer-contact"><a href="#contact">Обсудить задачу</a><p>Ленинградская область и Карелия. <br>Площадку выбираем под задачу команды.</p></div>
</div><div class="container footer-bottom"><span>© North Refresh, 2026</span><span>Подготовка · Сессия · План исполнения</span></div></footer>'''

def contact(compact=False):
    content = '''<section class="section contact-section" id="contact" aria-labelledby="contact-title"><div class="container contact-grid">
<div><p class="eyebrow light">Первый разговор</p><h2 id="contact-title">Обсудим задачу <br>вашей команды.</h2><p class="contact-lead">Расскажите, что нужно решить и кто участвует. Обсудим программу и подготовим предложение.</p></div>
<form id="contact-form" class="contact-form" action="https://formspree.io/f/moeangbe" method="post">
<h3>Оставьте контакт</h3><p class="form-intro">Свяжемся, чтобы обсудить задачу и формат работы.</p>
<div class="honeypot" aria-hidden="true"><label for="website">Оставьте это поле пустым</label><input id="website" name="_gotcha" type="text" tabindex="-1" autocomplete="off"></div>
<div class="form-row"><label for="name">Имя <span>*</span><input id="name" name="name" autocomplete="name" placeholder="Как к вам обращаться" required maxlength="120"></label><label for="company">Компания<input id="company" name="company" autocomplete="organization" placeholder="Название компании" maxlength="180"></label></div>
<label for="contact-detail">Email, телефон или Telegram <span>*</span><input id="contact-detail" name="contact" autocomplete="off" placeholder="Удобный способ связи" required minlength="5" maxlength="180" aria-describedby="contact-hint"></label><p class="field-hint" id="contact-hint">Достаточно одного контакта.</p>
<label for="task">Коротко о задаче <span class="optional">необязательно</span><textarea id="task" name="task" rows="3" placeholder="Что нужно обсудить или согласовать?" maxlength="4000"></textarea></label>
<p class="form-privacy">Контактные данные используем для ответа на запрос.</p>
<button class="button button-primary button-full" type="submit">Обсудить задачу <span aria-hidden="true">↗</span></button>
<p class="form-note" id="form-note" role="status" aria-live="polite">Обязательные поля — имя и контакт.</p>
<noscript><p class="form-note">После отправки откроется страница подтверждения заявки.</p></noscript>
</form></div></section>'''
    if compact:
        content = content.replace('Обсудим задачу <br>вашей команды.', 'Первый разговор')
    return content

def heading(kicker, title, lead=''):
    return f'<div class="section-heading"><p class="eyebrow">{kicker}</p><div><h2>{title}</h2>'+(f'<p class="section-lead">{lead}</p>' if lead else '')+'</div></div>'

def pagehero(kicker, title, lead, aside=''):
    return f'<section class="container page-hero"><p class="breadcrumb"><a href="/">Главная</a><span aria-hidden="true"> / </span>{kicker}</p><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="page-lead">{lead}</p><div class="hero-actions"><a class="button button-primary" href="#contact">Обсудить задачу <span aria-hidden="true">↗</span></a>{aside}</div></section>'

def write(path, title, description, content):
    schema = {'@context':'https://schema.org', '@graph':[{'@type':'Organization','@id':'https://northrefresh.ru/#organization','name':'North Refresh','url':'https://northrefresh.ru/'}, {'@type':'WebPage','name':title,'url':'https://northrefresh.ru'+path,'inLanguage':'ru-RU','publisher':{'@id':'https://northrefresh.ru/#organization'}}]}
    html = f'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} | North Refresh</title><meta name="description" content="{description}"><meta name="theme-color" content="#173d31">
<link rel="canonical" href="https://northrefresh.ru{path}"><link rel="icon" href="/favicon.svg?v={VERSION}" type="image/svg+xml" sizes="any">
<meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="North Refresh"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://northrefresh.ru{path}"><meta property="og:image" content="https://northrefresh.ru/north-real-fog.webp">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{title}"><meta name="twitter:description" content="{description}"><meta name="twitter:image" content="https://northrefresh.ru/north-real-fog.webp">
<link rel="preload" href="/fonts/manrope-cyrillic.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/fonts/cormorant-cyrillic.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="/site.css?v={VERSION}"><script defer src="/site.js?v={VERSION}"></script><script type="application/ld+json">{json.dumps(schema, ensure_ascii=False)}</script></head>
<body>{header(path)}<main id="content">{content}</main>{footer()}</body></html>'''
    dest = ROOT / path.strip('/') / 'index.html' if path != '/' else ROOT / 'index.html'
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html)

HOME = '''
<section class="container hero home-hero" id="top" aria-labelledby="hero-title">
<div class="hero-copy"><p class="eyebrow">North Refresh · для собственников, CEO и команд</p><h1 id="hero-title">Выездные стратегические сессии под задачу вашего бизнеса.</h1><p class="hero-lead">Готовим программу под вашу задачу, подбираем эксперта и организуем выезд. На сессии команда принимает решения и составляет план на 90 дней: действия, ответственные и сроки.</p><div class="hero-actions"><a class="button button-primary" href="#contact">Обсудить задачу</a><a class="text-link" href="#about">Как устроен продукт</a></div><p class="hero-note">Ленинградская область и Карелия · базовый формат — 3 дня</p></div>
<figure class="home-hero-image"><img src="/north-real-hero.webp" alt="Северное озеро и сосновый лес на закате" width="1200" height="1800" fetchpriority="high"><figcaption>Время для работы команды. <br>Программа начинается с вашей задачи.</figcaption></figure>
</section>
<section class="section home-about" id="about"><div class="container product-grid"><div><p class="eyebrow">Что такое North Refresh</p><h2>Сессия и весь выезд <br>в одном проекте.</h2><p class="section-lead">North Refresh — подготовка и проведение стратегической сессии вместе с организацией выезда для вашей команды.</p><p>Готовим рабочую программу, подбираем площадку, организуем проживание и питание. Продюсер координирует подготовку и работу на месте.</p><a class="text-link" href="/kak-my-rabotaem/">Как организуем работу</a></div><div class="home-situations"><h3>Когда это нужно</h3><ul><li>У руководителей разные приоритеты, а ресурсы общие.</li><li>Важное решение откладывается от совещания к совещанию.</li><li>Задачи переходят между отделами без ответственного за результат.</li><li>Предстоят изменения, для которых нужен согласованный план.</li></ul></div></div></section>
<section class="section result-section" id="result"><div class="container">'''+heading('Результат для компании', 'Результат сессии.')+'''
<div class="result-grid"><article><h3>Приоритеты</h3><p>Что делаем сейчас, что откладываем и почему.</p></article><article><h3>Протокол решений</h3><p>Принятые решения и условия их выполнения.</p></article><article><h3>План на 90 дней</h3><p>Действия, ответственные, сроки и критерии выполнения.</p></article></div><div class="result-example"><div class="example-caption"><h3>Одна строка плана</h3><span>Учебный пример</span></div><dl><div><dt>Действие</dt><dd>Согласовать экономику и бюджет пилота</dd></div><div><dt>Ответственный</dt><dd>Финансовый директор</dd></div><div><dt>Срок</dt><dd>День 7</dd></div><div><dt>Критерий выполнения</dt><dd>Утверждены расчёт маржи и лимит финансирования</dd></div></dl><a class="text-link" href="/programma/#roadmap">Посмотреть полный пример плана</a></div></div></section>
<section class="section" id="process"><div class="container">'''+heading('Как работаем', 'Как проходит работа.')+'''
<ol class="process-list"><li><span class="number">01</span><h3>Разбираем запрос</h3><p>Уточняем вопрос, участников и данные для решения.</p></li><li><span class="number">02</span><h3>Готовим сессию</h3><p>Согласуем специалиста, программу и ожидаемый результат.</p></li><li><span class="number">03</span><h3>Проводим выезд</h3><p>Команда сравнивает варианты и принимает решения. Мы координируем организацию.</p></li><li><span class="number">04</span><h3>Фиксируем действия</h3><p>Передаём итоги и план. По запросу проводим контрольные встречи.</p></li></ol><div class="section-tail"><p>Задачу, специалиста, программу и состав результатов согласуем с вами до выезда.</p><a class="text-link" href="/podbor-eksperta/">Как выбираем эксперта</a></div></div></section>
<section class="section budget-section home-budget" id="price"><div class="container budget-grid"><div><p class="eyebrow">Формат и бюджет</p><h2>Формат и стоимость.</h2><p class="section-lead">Подготовка и проведение сессии, рабочая площадка, проживание, питание и координация — в едином предложении.</p><a class="text-link" href="/kak-my-rabotaem/#scope">Состав проекта</a><img class="budget-landscape" src="/north-real-fog.webp" alt="Туман над лесом и озером на Севере" loading="lazy" width="1200" height="800"></div><div class="budget-card"><p class="eyebrow">Стоимость участия</p><strong class="budget-number participant-price"><span class="price-from">от</span> 80 000 <span class="price-unit">₽ / участника</span></strong><p class="budget-base">3 дня · 2 ночи · 12–24 участника</p><div class="budget-divider"></div><p class="project-total">Ориентир за базовый проект: <strong>1,44–1,92 млн ₽.</strong></p><p>Стоимость за участника зависит от размера команды, программы и площадки.</p><p>Транспорт и сопровождение после выезда рассчитываются отдельно. Договор с перевозчиком заказчик оформляет напрямую.</p><p class="small-note">Для небольшой команды или другой длительности — индивидуальный расчёт.</p><a class="button button-primary button-full" href="#contact">Обсудить задачу и бюджет</a></div></div></section>
<section class="section faq-section" id="faq"><div class="container faq-grid"><div><p class="eyebrow">Перед первым разговором</p><h2>Четыре вопроса <br>о работе с нами.</h2></div><div class="faq-list">
<details><summary>Можно приехать небольшой командой?</summary><p>Да. Состав зависит от того, кто принимает и исполняет решения. Для команды меньше 12 человек подготовим отдельную программу и смету.</p></details>
<details><summary>Кто будет вести сессию?</summary><p>После разбора задачи предложим ведущего и, если нужен, профильного эксперта. Его опыт, подход и роль согласуем с вами до подтверждения программы.</p></details>
<details><summary>Как работать с конфиденциальными данными?</summary><p>До передачи материалов согласуем условия конфиденциальности, доступ к данным и порядок фиксации и хранения результатов.</p></details>
<details><summary>Что происходит после выезда?</summary><p>Передаём итоговые материалы. При необходимости согласуем контрольные встречи, чтобы разобрать выполнение плана и препятствия. Объём и стоимость сопровождения указываем отдельно.</p></details>
</div></div></section>'''+contact()

PROCESS = pagehero('Как мы работаем', 'От запроса собственника <br>до плана исполнения', 'Согласуем задачу и ожидаемый результат до выезда. Подготовка, эксперт и программа должны соответствовать вопросу, который предстоит решить.')+'''
<section class="section section-topless"><div class="container steps-detail">
<article><div><span class="number">01 / ДИАГНОСТИКА</span><h2>Определить задачу</h2></div><div><p>Обсуждаем задачу: какое решение нужно принять, кто участвует и что мешает договориться.</p><ul><li>Ожидаемый результат и границы вопроса.</li><li>Участники, их полномочия и разные позиции.</li><li>Исходные данные и ограничения по ресурсам.</li></ul><p class="step-output"><strong>На выходе:</strong> согласованный запрос и перечень материалов для подготовки.</p></div></article>
<article><div><span class="number">02 / ПРОЕКТИРОВАНИЕ</span><h2>Собрать программу</h2></div><div><p>Подбираем ведущего и при необходимости профильного эксперта. Предлагаем последовательность рабочих блоков и документы, которые команда подготовит по итогам.</p><p>Длительность определяется задачей. Базовый выезд — три дня и две ночи; для другого состава команды и объёма работы делаем отдельный расчёт.</p><p class="step-output"><strong>На выходе:</strong> кандидат специалиста, программа, состав результатов и предварительная смета.</p><a class="text-link" href="/podbor-eksperta/">Порядок подбора эксперта <span aria-hidden="true">→</span></a></div></article>
<article><div><span class="number">03 / ПОДГОТОВКА</span><h2>Подготовить команду</h2></div><div><p>Согласуем необходимые интервью, материалы и данные компании. Уточняем вопросы, по которым позиции участников различаются, и правила работы с конфиденциальной информацией.</p><p>Продюсер параллельно согласует площадку, размещение, питание и график. Все включённые услуги и доплаты отражаются в предложении.</p><p class="step-output"><strong>На выходе:</strong> материалы для сессии, подробная программа и подтверждённые организационные условия.</p></div></article>
<article><div><span class="number">04 / СЕССИЯ</span><h2>Принять решения</h2></div><div><p>Сверяем факты, сравниваем варианты по согласованным критериям и обсуждаем ресурсы. Ведущий направляет обсуждение и фиксирует договорённости.</p><p>Решения принимают собственник и уполномоченные руководители. Если фактов недостаточно, определяем порядок дополнительной проверки.</p><p class="step-output"><strong>На выходе:</strong> выбранные приоритеты, протокол решений и план действий.</p></div></article>
<article><div><span class="number">05 / ПОСЛЕ ВЫЕЗДА</span><h2>Проверить исполнение</h2></div><div><p>Оформляем и передаём итоговые материалы. При согласованном сопровождении проводим контрольные встречи: проверяем первые действия, обсуждаем препятствия и обновляем план.</p><p>Количество встреч, период сопровождения, состав участников и стоимость определяются в предложении. </p><p class="step-output"><strong>На выходе:</strong> обновлённый план и график контрольных встреч.</p></div></article>
</div></section>
<section class="section result-section" id="scope"><div class="container">'''+heading('Состав проекта', 'Что согласуем <br>до подтверждения')+'''
<div class="scope-grid"><article><h3>Содержательная работа</h3><ul><li>Диагностика запроса и объём подготовки.</li><li>Программа, ведущий и профильные специалисты.</li><li>Проведение рабочих сессий.</li><li>Протокол решений и план исполнения.</li><li>Состав и бюджет последующего сопровождения.</li></ul></article><article><h3>Организация выезда</h3><ul><li>Площадка и закрытое рабочее пространство.</li><li>Проживание и тип размещения.</li><li>Питание и перерывы между сессиями.</li><li>Материалы, оборудование и координация.</li><li>Время прибытия и условия дополнительных услуг.</li></ul></article></div><div class="scope-note"><strong>Транспорт — отдельный договор.</strong><p>Помогаем выбрать перевозчика и согласовать расписание. Заказчик заключает договор и оплачивает перевозку напрямую. Дополнительные ночи, одноместное размещение и другие услуги указываем в смете; их состав зависит от выбранной комплектации.</p></div></div></section>
<section class="section"><div class="container responsibility-grid"><div><p class="eyebrow">Ответственность</p><h2>У каждой части <br>есть ответственный</h2></div><div><article><h3>Продюсер North Refresh</h3><p>Координирует проект, площадку, подрядчиков и организационные условия. Держит единый график подготовки и проведения.</p></article><article><h3>Ведущий рабочей части</h3><p>Проектирует сессии, работает с обсуждением и помогает оформить решения. Профильный эксперт привлекается, если задача требует специального опыта.</p></article><article><h3>Заказчик и управленческая команда</h3><p>Предоставляют исходные данные, принимают решения в рамках своих полномочий и выполняют согласованный план.</p></article></div></div></section>'''+contact()

EXPERT = pagehero('Подбор эксперта', 'Подберём ведущего <br>для вашей задачи.', 'Сначала разбираем вопрос компании. Затем предлагаем специалиста и объясняем, какой опыт и подход нужны для этой работы.')+'''
<section class="section section-topless"><div class="container">'''+heading('Роли в рабочей части', 'Разным вопросам <br>нужны разные специалисты')+'''
<div class="role-grid"><article><span class="number">01</span><h3>Фасилитатор</h3><p>Ведёт обсуждение, помогает сравнить варианты и договориться о решении.</p><div class="role-task">Когда нужен: разные приоритеты, затянувшиеся обсуждения, распределение ответственности.</div></article><article><span class="number">02</span><h3>Профильный эксперт</h3><p>Работает над профильным вопросом: экономикой продукта, продажами, структурой управления или операционными процессами.</p><div class="role-task">Когда нужен: для оценки вариантов требуется специальный опыт, которого не хватает внутри команды.</div></article></div><p class="section-lead narrow">В одном проекте роли могут сочетаться. Состав специалистов определяется после разбора задачи и отражается в смете.</p></div></section>
<section class="section result-section"><div class="container">'''+heading('Критерии выбора', 'Что проверяем <br>при подборе')+'''
<div class="situations-grid"><article><span class="number">01</span><h3>Соответствие задаче</h3><p>Проекты и опыт решения похожих бизнес-задач.</p></article><article><span class="number">02</span><h3>Уровень участников</h3><p>Опыт работы с собственниками, руководителями и разногласиями внутри команды.</p></article><article><span class="number">03</span><h3>Подход к подготовке</h3><p>Какие данные специалист запрашивает и как строит программу.</p></article><article><span class="number">04</span><h3>Качество фиксации</h3><p>Как специалист оформляет решения и план действий.</p></article></div></div></section>
<section class="section"><div class="container definition-grid"><div><p class="eyebrow">Согласование</p><h2>Вы выбираете <br>специалиста до сессии.</h2></div><div><p class="section-lead">До утверждения программы предоставляем профиль предложенного специалиста, описание его роли и подхода к задаче.</p><ol class="plain-list"><li>Разбираем запрос и определяем необходимый опыт.</li><li>Показываем опыт кандидата на похожих задачах.</li><li>Согласуем рабочие вопросы, подготовку и результаты.</li><li>Фиксируем участие и условия в предложении.</li></ol><p>Перед утверждением программы можно познакомиться со специалистом и обсудить задачу.</p><a class="text-link" href="/kak-my-rabotaem/">Как готовится весь проект <span aria-hidden="true">→</span></a></div></div></section>'''+contact()

PROGRAM = '<section class="container page-hero program-hero"><p class="breadcrumb"><a href="/">Главная</a> / Программа и результаты</p><p class="eyebrow">Программа и результаты</p><h1>Пример плана на 90 дней.</h1><p class="page-lead">Действия, ответственные, сроки и критерии выполнения. Ниже — программа сессии, на которой команда готовит такой план.</p><p class="demo-label">Учебный пример. Программу и план для вашей команды разрабатываем под задачу.</p></section>'+'''
<section class="section section-topless" id="roadmap"><div class="container">
<div class="table-wrap" role="region" aria-label="Пример плана исполнения" tabindex="0"><table class="roadmap-table" role="table"><caption>Учебный пример: подготовка пилота нового продукта</caption><thead><tr><th scope="col">Действие</th><th scope="col">Ответственный</th><th scope="col">Срок</th><th scope="col">Проверка результата</th></tr></thead><tbody><tr><td data-label="Действие">Согласовать экономику и лимит бюджета пилота</td><td data-label="Ответственный">Финансовый директор</td><td data-label="Срок">День 7</td><td data-label="Проверка результата">Утверждены расчёт маржи, расходы и лимит финансирования</td></tr><tr><td data-label="Действие">Определить клиентский сегмент и условия теста</td><td data-label="Ответственный">Коммерческий директор</td><td data-label="Срок">День 14</td><td data-label="Проверка результата">Зафиксированы сегмент, предложение и целевые показатели теста</td></tr><tr><td data-label="Действие">Провести пилот и собрать фактические данные</td><td data-label="Ответственный">Руководитель продукта</td><td data-label="Срок">День 45</td><td data-label="Проверка результата">Подготовлен отчёт: продажи, маржа, обратная связь и загрузка команды</td></tr><tr><td data-label="Действие">Принять решение о продолжении</td><td data-label="Ответственный">CEO и владельцы функций</td><td data-label="Срок">День 60</td><td data-label="Проверка результата">Решение сопоставлено с критериями, установленными до пилота</td></tr><tr><td data-label="Действие">Проверить выполнение решений квартала</td><td data-label="Ответственный">CEO</td><td data-label="Срок">День 90</td><td data-label="Проверка результата">Сверены план и факт, определены действия следующего периода</td></tr></tbody></table></div>
<div class="document-pair"><article><p class="eyebrow">Протокол решений</p><h3>Что фиксируем отдельно</h3><ul><li>Что утверждено и кем.</li><li>Какие инициативы отложены и почему.</li><li>Какие ограничения действуют.</li><li>Какие вопросы требуют дополнительных данных.</li></ul></article><article><p class="eyebrow">Контрольные встречи</p><h3>Как возвращаемся к плану</h3><p>На контрольной встрече разбираем выполненные действия, задержки и изменения в плане.</p><p>В примере — встречи на 30-й и 90-й день. График сопровождения включаем в предложение.</p></article></div></div></section>
<section class="section"><div class="container definition-grid"><div><p class="eyebrow">Исходная ситуация</p><h2>Инициатив много. <br>Ресурсы ограничены.</h2></div><div><p class="section-lead">У руководителей разные предложения на следующий квартал. Единого порядка запуска нет. Одни и те же люди нужны сразу нескольким проектам.</p><p><strong>Вопрос сессии:</strong> какие инициативы запускаем в ближайшие 90 дней, какие откладываем и кто отвечает за выполнение?</p><p><strong>До выезда:</strong> собираем перечень инициатив, доступные ресурсы, текущие показатели и ограничения. Уточняем позиции участников и полномочия для принятия решений.</p></div></div></section>
<section class="section result-section"><div class="container">'''+heading('Три дня / пример', 'От общей картины <br>к согласованным действиям')+'''
<div class="day-grid"><article><span class="number">ДЕНЬ 1</span><h3>Факты и критерии</h3><p>Сверяем ситуацию, список инициатив и ограничения. Определяем критерии выбора и вопросы, по которым взгляды расходятся.</p><div class="day-output"><strong>Итог</strong><p>Общий список вариантов и согласованные критерии приоритета.</p></div></article><article><span class="number">ДЕНЬ 2</span><h3>Выбор и ресурсы</h3><p>Сравниваем варианты, обсуждаем риски и зависимости. Выбираем инициативы, на которые команда готова выделить ресурсы.</p><div class="day-output"><strong>Итог</strong><p>Приоритеты квартала, отложенные инициативы и предварительное распределение ресурсов.</p></div></article><article><span class="number">ДЕНЬ 3</span><h3>План исполнения</h3><p>Назначаем владельцев инициатив, определяем первые действия, сроки и критерии выполнения. Согласуем контрольные точки.</p><div class="day-output"><strong>Итог</strong><p>Протокол решений и план на 90 дней.</p></div></article></div><p class="small-note">Перерывы, питание и время вне рабочих блоков закладываем в график. Рабочая нагрузка определяется задачей и составом команды.</p></div></section>
'''+contact()

CONTACTS = '<section class="container page-hero contact-page-hero"><p class="breadcrumb"><a href="/">Главная</a> / Контакты</p><h1>Обсудить задачу.</h1></section>'+contact(compact=True)

write('/', 'Выездные стратегические сессии для собственников и команд', 'North Refresh: диагностика задачи, подбор эксперта, организация выездной сессии и план на 90 дней с ответственными, сроками и метриками.', HOME)
write('/kak-my-rabotaem/', 'Как мы готовим и проводим стратегическую сессию', 'Диагностика, программа, эксперт, подготовка команды, проведение и сопровождение. Состав работы и ответственность North Refresh.', PROCESS)
write('/podbor-eksperta/', 'Подбор эксперта и фасилитатора под задачу компании', 'Критерии подбора и согласования специалиста для стратегической сессии. Роли фасилитатора, профильного эксперта и заказчика.', EXPERT)
write('/programma/', 'Пример программы стратегической сессии и плана на 90 дней', 'Демонстрационная задача, логика трёх дней, протокол решений и пример плана исполнения. Учебный пример North Refresh.', PROGRAM)
write('/kontakty/', 'Обсудить задачу управленческой команды', 'Свяжитесь с North Refresh для обсуждения выездной стратегической сессии. Задача, ожидаемые результаты, состав команды и бюджет.', CONTACTS)

# Legacy routes retain inbound links without retaining the previous product copy.
for path, target in [('/korporativnyy-retrit/', '/'), ('/strategicheskaya-sessiya/', '/')]:
    dest = ROOT / path.strip('/') / 'index.html'
    dest.write_text(f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>North Refresh — стратегические сессии</title><link rel="canonical" href="https://northrefresh.ru{target}"><meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url={target}"></head><body><p>Страница обновлена. <a href="{target}">Перейти на сайт North Refresh</a></p></body></html>''')

notfound = pagehero('Страница не найдена', 'Вернёмся <br>к вашей задаче.', 'Возможно, адрес изменился. На главной странице — продукт, процесс работы и способы связи.', '<a class="text-link" href="/">На главную <span aria-hidden="true">→</span></a>')
write('/404/', 'Страница не найдена', 'Перейти на главную страницу North Refresh.', notfound)
(ROOT/'404.html').write_text((ROOT/'404/index.html').read_text())
urls = ['/', '/kak-my-rabotaem/', '/podbor-eksperta/', '/programma/', '/kontakty/']
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>https://northrefresh.ru{p}</loc></url>\n' for p in urls)+'</urlset>\n')
print('Built 5 pages, 2 legacy redirects and 404; updated sitemap.')
